# Generated by Django 5.1.6 on 2025-03-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloguser',
            options={'ordering': ['is_active', 'last_login']},
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='avatar',
            field=models.CharField(default='/media/avatar/default.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
