# Generated by Django 5.1.6 on 2025-03-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
