# Generated by Django 5.1.6 on 2025-03-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_cover_image_remove_blog_is_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like_count',
        ),
    ]
